### ISSUE TITLE
尊敬的作者，您好，A question about HTTP request parsing.

### ISSUE THREAD

**Issue by tomatowithpotato** [InnovatorZhang/my-WebServer#1]
本人有幸得观作者的改良代码，甚是欣赏，以下是我的一些理解和疑问

HttpRequest::parse函数内的while循环，会先查找crlf来获取一行，然后在switch语句里走解析流程，最后通过lineEnd == buff.beginWrite()判断请求是否完整，不完整就break退出。

但不完整的请求必然会解析失败，就会走BAD_REQUEST

所以我的看法是可以把lineEnd == buff.beginWrite()放在解析之前，这样就合理一些

**Comment by InnovatorZhang** [comment]
> 本人有幸得观作者的改良代码，甚是欣赏，以下是我的一些理解和疑问
> 
> HttpRequest::parse函数内的while循环，会先查找crlf来获取一行，然后在switch语句里走解析流程，最后通过lineEnd == buff.beginWrite()判断请求是否完整，不完整就break退出。
> 
> 但不完整的请求必然会解析失败，就会走BAD_REQUEST
> 
> 所以我的看法是可以把lineEnd == buff.beginWrite()放在解析之前，这样就合理一些

我刚才又试了一下你提出的解决方法，我发现这样会有问题，因为最后的post请求体实际上是没有 CRLF作为结尾的，如果按照你说的这样将lineEnd == buff.beginWrite()判断放在解析之前，会导致无法解析post请求，后端会一直等待客户端发来新请求。你可以将将代码放到switch前编译运行试一试。

**Comment by tomatowithpotato** [comment]
> > 本人有幸得观作者的改良代码，甚是欣赏，以下是我的一些理解和疑问
> > HttpRequest::parse函数内的while循环，会先查找crlf来获取一行，然后在switch语句里走解析流程，最后通过lineEnd == buff.beginWrite()判断请求是否完整，不完整就break退出。
> > 但不完整的请求必然会解析失败，就会走BAD_REQUEST
> > 所以我的看法是可以把lineEnd == buff.beginWrite()放在解析之前，这样就合理一些
> 
> 我刚才又试了一下你提出的解决方法，我发现这样会有问题，因为最后的post请求体实际上是没有 CRLF作为结尾的，如果按照你说的这样将lineEnd == buff.beginWrite()判断放在解析之前，会导致无法解析post请求，后端会一直等待客户端发来新请求。你可以将将代码放到switch前编译运行试一试。

确实如此，因为只有请求头才会有crlf作为结束，所以我的提议只能解决请求头没读取完的问题
如果要判断请求体的结束，可能得结合请求头里的content-length字段才行了

**Comment by InnovatorZhang** [comment]
> 

是的，刚才我修改了解析post请求的一部分代码，就是结合你说的请求头中的content-length字段判断请求体是否接受完毕，接受完毕的话就进入到请求体的解析，未接收完毕则返回NO_REQUEST继续等待数据。现在可以处理请求体未接受完整这种情况了。

**Comment by InnovatorZhang** [comment]
> > > 本人有幸得观作者的改良代码，甚是欣赏，以下是我的一些理解和疑问
> > > HttpRequest::parse函数内的while循环，会先查找crlf来获取一行，然后在switch语句里走解析流程，最后通过lineEnd == buff.beginWrite()判断请求是否完整，不完整就break退出。
> > > 但不完整的请求必然会解析失败，就会走BAD_REQUEST
> > > 所以我的看法是可以把lineEnd == buff.beginWrite()放在解析之前，这样就合理一些
> > 
> > 
> > 我刚才又试了一下你提出的解决方法，我发现这样会有问题，因为最后的post请求体实际上是没有 CRLF作为结尾的，如果按照你说的这样将lineEnd == buff.beginWrite()判断放在解析之前，会导致无法解析post请求，后端会一直等待客户端发来新请求。你可以将将代码放到switch前编译运行试一试。
> 
> 确实如此，因为只有请求头才会有crlf作为结束，所以我的提议只能解决请求头没读取完的问题 如果要判断请求体的结束，可能得结合请求头里的content-length字段才行了

是的，刚才我修改了解析post请求的一部分代码，就是结合你说的请求头中的content-length字段判断请求体是否接受完毕，接受完毕的话就进入到请求体的解析，未接收完毕则返回NO_REQUEST继续等待数据。现在可以处理请求体未接受完整这种情况了。
